export { default as Navbar } from "./Navbar";
export { default as Hero } from "./Hero";
export { default as Topics } from "./Topics";
export { default as Courses } from "./Courses";
export { default as About } from "./About";
export { default as Partners } from "./Partners";
export { default as Testimonials } from "./Testimonials";
export { default as Service } from "./Service";
export { default as Footer } from "./Footer";
